# Generated by Django 5.1.6 on 2026-02-07 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAdvertencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Não uso de EPI, Atraso Injustificado', max_length=100, verbose_name='Motivo da Falta')),
                ('descricao_padrao', models.TextField(blank=True, help_text='Texto jurídico ou técnico padrão para sair na impressão', verbose_name='Texto Padrão para Documento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Advertencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_incidente', models.DateField(verbose_name='Data do Ocorrido')),
                ('detalhes', models.TextField(blank=True, verbose_name='Observações Específicas')),
                ('reincidente', models.BooleanField(default=False, verbose_name='É reincidente?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertencias', to='core.funcionario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoadvertencia', verbose_name='Motivo')),
            ],
        ),
    ]
