# Generated by Django 5.1.6 on 2026-01-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(default='2024-01-01', verbose_name='Data de Admissão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
