# Generated by Django 5.1.6 on 2026-01-31 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_funcionario_ativo_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('epis_obrigatorios', models.TextField(blank=True, help_text='Ex: Capacete, Bota, Luva', verbose_name='EPIs Obrigatórios')),
                ('nrs_obrigatorias', models.TextField(blank=True, help_text='Ex: NR-10, NR-35', verbose_name='NRs Necessárias')),
                ('vacinas_necessarias', models.TextField(blank=True, help_text='Ex: Tétano, Hepatite', verbose_name='Vacinas')),
                ('treinamentos', models.TextField(blank=True, help_text='Ex: Trabalho em Altura', verbose_name='Treinamentos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.setor', verbose_name='Setor de Trabalho'),
        ),
    ]
