# Generated by Django 5.1.6 on 2026-01-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_setor_alter_funcionario_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaRegulamentadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='setor',
            name='epis_obrigatorios',
            field=models.TextField(blank=True, verbose_name='EPIs Obrigatórios'),
        ),
        migrations.RemoveField(
            model_name='setor',
            name='nrs_obrigatorias',
        ),
        migrations.AlterField(
            model_name='setor',
            name='treinamentos',
            field=models.TextField(blank=True, verbose_name='Treinamentos'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='vacinas_necessarias',
            field=models.TextField(blank=True, verbose_name='Vacinas'),
        ),
        migrations.AddField(
            model_name='setor',
            name='nrs_obrigatorias',
            field=models.ManyToManyField(blank=True, to='core.normaregulamentadora', verbose_name='NRs Aplicáveis'),
        ),
    ]
