# Generated by Django 5.1.6 on 2026-02-07 05:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_setor_vacinas_necessarias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extintor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_patrimonial', models.CharField(help_text='Ex: EXT-01', max_length=50, verbose_name='Cód. Patrimonial')),
                ('numero_serie', models.CharField(max_length=100, verbose_name='Nº de Série Cilindro')),
                ('classe', models.CharField(choices=[('A', 'Classe A'), ('B', 'Classe B'), ('C', 'Classe C'), ('D', 'Classe D'), ('K', 'Classe K'), ('BC', 'Classes B/C'), ('ABC', 'Classes A/B/C')], max_length=5, verbose_name='Classe')),
                ('agente', models.CharField(choices=[('AGUA', 'Água Pressurizada'), ('PQS', 'Pó Químico Seco (PQS)'), ('CO2', 'Gás Carbônico (CO2)'), ('ESPUMA', 'Espuma Mecânica'), ('ACETATO', 'Acetato de Potássio')], max_length=20, verbose_name='Agente Extintor')),
                ('capacidade', models.IntegerField(verbose_name='Capacidade (kg/L)')),
                ('classe_risco', models.CharField(help_text='Ex: Risco Leve, Risco de Elétrica', max_length=100, verbose_name='Risco do Local')),
                ('data_ultima_manutencao', models.DateField(verbose_name='Última Recarga')),
                ('data_proxima_manutencao', models.DateField(verbose_name='Vencimento Recarga')),
                ('data_teste_hidrostatico', models.DateField(verbose_name='Vencimento Teste Hidrostático (5 anos)')),
                ('empresa_mantenedora', models.CharField(blank=True, max_length=200)),
                ('numero_lacre', models.CharField(blank=True, max_length=50)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Em Manutenção'), ('RESERVA', 'Reserva'), ('CONDENADO', 'Condenado')], default='ATIVO', max_length=20, verbose_name='Situação Atual')),
                ('altura_instalacao', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Altura (m)')),
                ('sinalizacao_ok', models.BooleanField(default=True, verbose_name='Sinalização OK?')),
                ('acesso_livre', models.BooleanField(default=True, verbose_name='Acesso Desobstruído?')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.localizacao', verbose_name='Local Físico')),
            ],
        ),
        migrations.CreateModel(
            name='InspecaoExtintor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao', models.DateField(default=django.utils.timezone.now)),
                ('responsavel', models.CharField(max_length=150)),
                ('lacre_intacto', models.BooleanField(default=True, verbose_name='Lacre Intacto?')),
                ('manometro_pressao_ok', models.BooleanField(default=True, verbose_name='Pressão OK?')),
                ('sinalizacao_visivel', models.BooleanField(default=True, verbose_name='Sinalização Visível?')),
                ('acesso_livre', models.BooleanField(default=True, verbose_name='Acesso Livre?')),
                ('mangueira_integra', models.BooleanField(default=True, verbose_name='Mangueira Íntegra?')),
                ('observacoes', models.TextField(blank=True)),
                ('extintor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes', to='core.extintor')),
            ],
        ),
    ]
