# Generated by Django 5.1.6 on 2026-02-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fotoinspecao'),
    ]

    operations = [
        migrations.AddField(
            model_name='extintor',
            name='qrcode_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes_extintores/', verbose_name='QR Code Registrado'),
        ),
    ]
