# Generated by Django 5.1.6 on 2026-02-07 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_extintor_qrcode_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HIDRANTE', 'Hidrante'), ('MANGUEIRA', 'Mangueira de Incêndio'), ('ALARME', 'Alarme / Botoeira'), ('LUZ', 'Iluminação de Emergência'), ('PLACA', 'Sinalização / Placa'), ('PORTA', 'Porta Corta-Fogo'), ('OUTRO', 'Outros')], max_length=20, verbose_name='Tipo de Equipamento')),
                ('nome', models.CharField(help_text='Ex: Hidrante 01, Luz do Corredor', max_length=100, verbose_name='Identificação')),
                ('data_instalacao', models.DateField(blank=True, null=True, verbose_name='Data de Instalação')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Validade / Próxima Manutenção')),
                ('especificacao', models.CharField(blank=True, help_text='Ex: 15 metros (para mangueira), 30 LEDs (para luz)', max_length=255, verbose_name='Especificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='outros_equipamentos/')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.localizacao', verbose_name='Localização')),
            ],
        ),
        migrations.CreateModel(
            name='InspecaoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao', models.DateField(default=django.utils.timezone.now)),
                ('responsavel', models.CharField(max_length=150)),
                ('item_integro', models.BooleanField(default=True, verbose_name='Item Íntegro/Sem Danos?')),
                ('acesso_livre', models.BooleanField(default=True, verbose_name='Acesso Livre?')),
                ('sinalizacao_ok', models.BooleanField(default=True, verbose_name='Sinalização OK?')),
                ('teste_funcional', models.BooleanField(default=True, verbose_name='Teste de Funcionamento OK?')),
                ('observacoes', models.TextField(blank=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes', to='core.equipamento')),
            ],
        ),
    ]
