# Generated by Django 5.1.6 on 2026-02-07 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_equipamento_inspecaoequipamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoInspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='inspecoes_equipamentos/', verbose_name='Arquivo/Foto')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('inspecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.inspecaoequipamento')),
            ],
        ),
    ]
