# Generated by Django 5.1.6 on 2026-02-07 19:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_arquivoinspecao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='meses_reforco',
            field=models.IntegerField(default=0, help_text='0 para dose única ou sem reforço automático', verbose_name='Reforço em (meses)'),
        ),
        migrations.RemoveField(
            model_name='setor',
            name='epis_obrigatorios',
        ),
        migrations.AlterField(
            model_name='vacina',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.CreateModel(
            name='ControleVacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField(verbose_name='Data da Aplicação')),
                ('data_proximo_reforco', models.DateField(blank=True, null=True, verbose_name='Próximo Reforço')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='vacinas_comprovantes/', verbose_name='Comprovante (Foto/PDF)')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='core.funcionario')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vacina')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField(default=django.utils.timezone.now)),
                ('quantidade', models.IntegerField(default=1)),
                ('ca_registrado', models.CharField(max_length=50, verbose_name='CA na Entrega')),
                ('validade_ca', models.DateField(verbose_name='Validade do CA')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de Devolução/Troca')),
                ('termo_assinado', models.FileField(blank=True, null=True, upload_to='epis_termos/', verbose_name='Ficha Assinada')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.epi', verbose_name='Item do Estoque')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_entregues', to='core.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='TreinamentoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_treinamento', models.CharField(max_length=200, verbose_name='Nome do Curso/Treinamento')),
                ('data_realizacao', models.DateField(verbose_name='Data Realização')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='treinamentos_certificados/', verbose_name='Certificado (PDF/Foto)')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos', to='core.funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='setor',
            name='epis_obrigatorios',
            field=models.ManyToManyField(blank=True, to='core.tipoepi', verbose_name='EPIs Obrigatórios por Tipo'),
        ),
    ]
