# Generated by Django 5.1.6 on 2026-02-07 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_funcionario_motivo_afastamento_funcionario_situacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcidenteTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acidente', models.DateField(verbose_name='Data do Acidente')),
                ('hora_acidente', models.TimeField(verbose_name='Hora')),
                ('local', models.CharField(max_length=255, verbose_name='Local do Acidente')),
                ('descricao_motivo', models.TextField(verbose_name='Descrição do Ocorrido / Motivo')),
                ('arquivo_evidencia', models.FileField(blank=True, null=True, upload_to='acidentes_arquivos/', verbose_name='Fotos/CAT')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acidentes', to='core.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_retorno', models.DateField(blank=True, null=True, verbose_name='Data de Retorno (Previsão ou Real)')),
                ('motivo', models.TextField(verbose_name='Motivo / CID')),
                ('laudo', models.FileField(blank=True, null=True, upload_to='afastamentos_laudos/', verbose_name='Laudo Médico (PDF/Foto)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamentos', to='core.funcionario')),
            ],
        ),
    ]
