# Generated by Django 5.1.6 on 2026-02-08 18:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tipoespecialidade_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epi',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='codigo_unico',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='tamanho',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='tipo',
        ),
        migrations.AddField(
            model_name='epi',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='arquivo_evidencia',
            field=models.FileField(blank=True, null=True, upload_to='acidentes_arquivos/'),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='descricao_motivo',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='data_retorno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='laudo',
            field=models.FileField(blank=True, null=True, upload_to='afastamentos_laudos/'),
        ),
        migrations.AlterField(
            model_name='arquivoinspecao',
            name='arquivo',
            field=models.FileField(upload_to='inspecoes_equipamentos/'),
        ),
        migrations.AlterField(
            model_name='controlevacina',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='vacinas_comprovantes/', verbose_name='Comprovante'),
        ),
        migrations.AlterField(
            model_name='epi',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.localizacao', verbose_name='Localização Física'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_instalacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='especificacao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='localizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.localizacao'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('HIDRANTE', 'Hidrante'), ('MANGUEIRA', 'Mangueira'), ('ALARME', 'Alarme'), ('LUZ', 'Luz Emergência'), ('PLACA', 'Placa'), ('PORTA', 'Porta Corta-Fogo'), ('OUTRO', 'Outros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='acesso_livre',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='agente',
            field=models.CharField(choices=[('AGUA', 'Água'), ('PQS', 'Pó Químico'), ('CO2', 'CO2'), ('ESPUMA', 'Espuma'), ('ACETATO', 'Acetato')], max_length=20),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='altura_instalacao',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='classe',
            field=models.CharField(choices=[('A', 'Classe A'), ('B', 'Classe B'), ('C', 'Classe C'), ('D', 'Classe D'), ('K', 'Classe K'), ('BC', 'Classes B/C'), ('ABC', 'Classes A/B/C')], max_length=5),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='classe_risco',
            field=models.CharField(max_length=100, verbose_name='Risco do Local'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='codigo_patrimonial',
            field=models.CharField(max_length=50, verbose_name='Cód. Patrimonial'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='data_teste_hidrostatico',
            field=models.DateField(verbose_name='Vencimento Teste Hidrostático'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='localizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.localizacao'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='numero_serie',
            field=models.CharField(max_length=100, verbose_name='Nº Série'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='qrcode_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes_extintores/'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='sinalizacao_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='situacao',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Em Manutenção'), ('RESERVA', 'Reserva'), ('CONDENADO', 'Condenado')], default='ATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='fotoinspecao',
            name='imagem',
            field=models.ImageField(upload_to='inspecoes_extintores/'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='motivo_afastamento',
            field=models.TextField(blank=True, verbose_name='Detalhes do Afastamento/Desligamento'),
        ),
        migrations.AlterField(
            model_name='inspecaoequipamento',
            name='acesso_livre',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inspecaoequipamento',
            name='item_integro',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inspecaoequipamento',
            name='sinalizacao_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inspecaoequipamento',
            name='teste_funcional',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inspecaoextintor',
            name='acesso_livre',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inspecaoextintor',
            name='lacre_intacto',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inspecaoextintor',
            name='mangueira_integra',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inspecaoextintor',
            name='manometro_pressao_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inspecaoextintor',
            name='sinalizacao_visivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produtoquimico',
            name='data_fabricacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtoquimico',
            name='data_validade',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='produtoquimico',
            name='fabricante',
            field=models.CharField(max_length=200, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='produtoquimico',
            name='fispq',
            field=models.FileField(blank=True, null=True, upload_to='produtos_quimicos_fispq/'),
        ),
        migrations.AlterField(
            model_name='produtoquimico',
            name='foto_rotulo',
            field=models.ImageField(blank=True, null=True, upload_to='produtos_quimicos_fotos/'),
        ),
        migrations.AlterField(
            model_name='produtoquimico',
            name='localizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.localizacao'),
        ),
        migrations.AlterField(
            model_name='produtoquimico',
            name='lote',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='produtoquimico',
            name='quantidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='produtoquimico',
            name='riscos',
            field=models.TextField(verbose_name='Riscos'),
        ),
        migrations.AlterField(
            model_name='produtoquimico',
            name='telefone_emergencia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='treinamentofuncionario',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='treinamentos_certificados/'),
        ),
        migrations.CreateModel(
            name='CategoriaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Capacete, Luva, Bota', max_length=100, verbose_name='Categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MarcaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Marca')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', '➕ Entrada (Compra/Devolução)'), ('SAIDA', '➖ Saída (Entrega/Descarte)')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_movimento', models.DateField(default=django.utils.timezone.now)),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Motivo/Detalhes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='core.epi')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario', verbose_name='Funcionário')),
            ],
        ),
        migrations.CreateModel(
            name='TamanhoEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(help_text='Ex: P, M, G, 40, 42', max_length=20, verbose_name='Tamanho')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
    ]
