# Generated by Django 5.1.6 on 2026-02-10 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Função Específica'),
        ),
    ]
