# Generated by Django 5.1.6 on 2026-02-07 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipoadvertencia_advertencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='vacinas_necessarias',
        ),
        migrations.AlterField(
            model_name='advertencia',
            name='detalhes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='epi',
            name='tamanho',
            field=models.CharField(max_length=20, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Local'),
        ),
        migrations.AlterField(
            model_name='tipoadvertencia',
            name='descricao_padrao',
            field=models.TextField(blank=True, verbose_name='Texto Padrão'),
        ),
        migrations.AlterField(
            model_name='tipoadvertencia',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Motivo da Falta'),
        ),
        migrations.AlterField(
            model_name='tipoepi',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Tipo'),
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Vacina')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição/Periodicidade')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='setor',
            name='vacinas_padrao',
            field=models.ManyToManyField(blank=True, to='core.vacina', verbose_name='Vacinas Obrigatórias'),
        ),
    ]
