# Generated by Django 5.1.6 on 2026-02-10 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_cargo_alter_funcionario_funcao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='epis',
            field=models.ManyToManyField(blank=True, to='core.epi', verbose_name='EPIs Padrão'),
        ),
        migrations.AddField(
            model_name='setor',
            name='exames',
            field=models.ManyToManyField(blank=True, to='core.tipoexame', verbose_name='Exames Padrão'),
        ),
        migrations.AddField(
            model_name='setor',
            name='vacinas',
            field=models.ManyToManyField(blank=True, to='core.vacina', verbose_name='Vacinas Padrão'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='normas',
            field=models.ManyToManyField(blank=True, to='core.normaregulamentadora', verbose_name='NRs Padrão'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='riscos',
            field=models.ManyToManyField(blank=True, to='core.riscoocupacional', verbose_name='Riscos Padrão do Setor'),
        ),
        migrations.CreateModel(
            name='PGR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
