# Generated by Django 5.1.6 on 2026-02-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_setor_epis_setor_exames_setor_vacinas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='epis',
            field=models.ManyToManyField(blank=True, to='core.tipoepi', verbose_name='EPIs Padrão (Tipos)'),
        ),
    ]
