# Generated by Django 5.1.6 on 2026-02-10 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_setor_epis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epi',
            old_name='marca',
            new_name='fabricante',
        ),
        migrations.AddField(
            model_name='tipoepi',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='core.categoriaepi'),
        ),
    ]
