# Generated by Django 5.1.6 on 2026-02-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vacina_meses_reforco_remove_setor_epis_obrigatorios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='motivo_afastamento',
            field=models.TextField(blank=True, help_text='Preencher apenas se estiver afastado ou desligado.', verbose_name='Detalhes do Afastamento/Desligamento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='situacao',
            field=models.CharField(choices=[('ATIVO', '✅ Em Exercício'), ('FERIAS', '🏖️ Férias'), ('AFASTADO', '🏥 Afastado (INSS/Médico)'), ('LICENCA', '👶 Licença Maternidade/Paternidade'), ('SUSPENSO', '⚠️ Suspenso'), ('DESLIGADO', '❌ Desligado')], default='ATIVO', max_length=20, verbose_name='Situação Atual'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Cadastro Ativo no Sistema?'),
        ),
    ]
