# Generated by Django 5.1.6 on 2026-02-07 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_acidentetrabalho_afastamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoQuimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('fabricante', models.CharField(max_length=200, verbose_name='Fabricante/Fornecedor')),
                ('riscos', models.TextField(help_text='Ex: Inflamável, Corrosivo, Tóxico...', verbose_name='Riscos e Perigos')),
                ('telefone_emergencia', models.CharField(max_length=50, verbose_name='Tel. Emergência (Vazamentos)')),
                ('lote', models.CharField(blank=True, max_length=50, verbose_name='Nº do Lote')),
                ('data_fabricacao', models.DateField(blank=True, null=True, verbose_name='Data de Fabricação')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('quantidade', models.CharField(help_text='Ex: 50 Litros, 10 Caixas', max_length=50, verbose_name='Quantidade Atual')),
                ('fispq', models.FileField(blank=True, null=True, upload_to='produtos_quimicos_fispq/', verbose_name='FISPQ (PDF)')),
                ('foto_rotulo', models.ImageField(blank=True, null=True, upload_to='produtos_quimicos_fotos/', verbose_name='Foto do Rótulo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.localizacao', verbose_name='Local de Armazenamento')),
            ],
        ),
    ]
