# Generated by Django 5.1.6 on 2026-02-08 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_epi_ca_remove_epi_codigo_unico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epi',
            name='ca',
            field=models.PositiveIntegerField(default=0, help_text='Somente números', verbose_name='C.A.'),
        ),
        migrations.AddField(
            model_name='epi',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categoriaepi', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='epi',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do CA'),
        ),
        migrations.AddField(
            model_name='epi',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.marcaepi', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='epi',
            name='modelo',
            field=models.CharField(blank=True, help_text='Ex: Raspa, Vaqueta, PVC', max_length=150, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='epi',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Qtd Atual'),
        ),
        migrations.AddField(
            model_name='epi',
            name='quantidade_minima',
            field=models.PositiveIntegerField(default=5, verbose_name='Qtd Mínima'),
        ),
        migrations.AddField(
            model_name='epi',
            name='tamanho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tamanhoepi', verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='epi',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.localizacao', verbose_name='Localização Física'),
        ),
    ]
