# Generated by Django 5.1.6 on 2026-02-08 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_epi_ca_epi_categoria_epi_data_validade_epi_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios/'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='motivo_afastamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.setor'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='situacao',
            field=models.CharField(choices=[('ATIVO', '✅ Em Exercício'), ('FERIAS', '🏖️ Férias'), ('AFASTADO', '🏥 Afastado (INSS/Médico)'), ('LICENCA', '👶 Licença Maternidade/Paternidade'), ('SUSPENSO', '⚠️ Suspenso'), ('DESLIGADO', '❌ Desligado')], default='ATIVO', max_length=20),
        ),
    ]
