# Generated by Django 5.1.6 on 2026-02-08 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_funcionario_data_nascimento_funcionario_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiscoOcupacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FISICO', 'Físico'), ('QUIMICO', 'Químico'), ('BIOLOGICO', 'Biológico'), ('ERGONOMICO', 'Ergonômico'), ('ACIDENTE', 'Acidente/Mecânico')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='afastamento',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='arquivoinspecao',
            name='data_upload',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='data_instalacao',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='especificacao',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='extintor',
            name='empresa_mantenedora',
        ),
        migrations.RemoveField(
            model_name='extintor',
            name='numero_lacre',
        ),
        migrations.RemoveField(
            model_name='fotoinspecao',
            name='data_upload',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='inspecaoequipamento',
            name='acesso_livre',
        ),
        migrations.RemoveField(
            model_name='inspecaoequipamento',
            name='item_integro',
        ),
        migrations.RemoveField(
            model_name='inspecaoequipamento',
            name='sinalizacao_ok',
        ),
        migrations.RemoveField(
            model_name='inspecaoequipamento',
            name='teste_funcional',
        ),
        migrations.RemoveField(
            model_name='inspecaoextintor',
            name='acesso_livre',
        ),
        migrations.RemoveField(
            model_name='inspecaoextintor',
            name='sinalizacao_visivel',
        ),
        migrations.RemoveField(
            model_name='produtoquimico',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='produtoquimico',
            name='data_fabricacao',
        ),
        migrations.RemoveField(
            model_name='produtoquimico',
            name='foto_rotulo',
        ),
        migrations.RemoveField(
            model_name='produtoquimico',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='produtoquimico',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='produtoquimico',
            name='riscos',
        ),
        migrations.RemoveField(
            model_name='produtoquimico',
            name='telefone_emergencia',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='epis_obrigatorios',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='nrs_obrigatorias',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='treinamentos',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='vacinas_padrao',
        ),
        migrations.AddField(
            model_name='acidentetrabalho',
            name='cat_emitida',
            field=models.BooleanField(default=False, verbose_name='CAT Emitida?'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='qrcode_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspecaoequipamento',
            name='status',
            field=models.CharField(default='OK', max_length=20),
        ),
        migrations.AddField(
            model_name='produtoquimico',
            name='classificacao',
            field=models.CharField(default='Geral', max_length=100),
        ),
        migrations.AddField(
            model_name='setor',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setor',
            name='normas',
            field=models.ManyToManyField(blank=True, to='core.normaregulamentadora'),
        ),
        migrations.AddField(
            model_name='setor',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='arquivo_evidencia',
            field=models.FileField(blank=True, null=True, upload_to='acidentes_arquivos/', verbose_name='Arquivo/Evidência'),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='descricao_motivo',
            field=models.TextField(verbose_name='Descrição do Ocorrido'),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='hora_acidente',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='acidentetrabalho',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local do Acidente'),
        ),
        migrations.AlterField(
            model_name='advertencia',
            name='data_incidente',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='advertencia',
            name='detalhes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='advertencia',
            name='reincidente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertencia',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoadvertencia'),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='motivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='categoriaepi',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='controlevacina',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='vacinas_comprovantes/'),
        ),
        migrations.AlterField(
            model_name='controlevacina',
            name='data_aplicacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='controlevacina',
            name='data_proximo_reforco',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='ca_registrado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='epi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.epi'),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='termo_assinado',
            field=models.FileField(blank=True, null=True, upload_to='epis_termos/'),
        ),
        migrations.AlterField(
            model_name='entregaepi',
            name='validade_ca',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='epi',
            name='ca',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='epi',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categoriaepi'),
        ),
        migrations.AlterField(
            model_name='epi',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epi',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.localizacao'),
        ),
        migrations.AlterField(
            model_name='epi',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.marcaepi'),
        ),
        migrations.AlterField(
            model_name='epi',
            name='modelo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='epi',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='epi',
            name='quantidade_minima',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='epi',
            name='tamanho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tamanhoepi'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('HIDRANTE', 'Hidrante'), ('ALARME', 'Alarme'), ('LUZ', 'Luz Emergência')], max_length=20),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='agente',
            field=models.CharField(choices=[('AGUA', 'Água'), ('PQS', 'Pó Químico'), ('CO2', 'CO2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='altura_instalacao',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='capacidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='classe',
            field=models.CharField(choices=[('A', 'Classe A'), ('BC', 'Classes B/C'), ('ABC', 'Classes A/B/C')], max_length=5),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='classe_risco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='codigo_patrimonial',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='data_proxima_manutencao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='data_teste_hidrostatico',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='data_ultima_manutencao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='numero_serie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='situacao',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Manutenção')], default='ATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='horario_atendimento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='observacao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', '➕ Entrada'), ('SAIDA', '➖ Saída')], max_length=10),
        ),
        migrations.AlterField(
            model_name='produtoquimico',
            name='fabricante',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produtoquimico',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tamanhoepi',
            name='tamanho',
            field=models.CharField(max_length=20, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='tipoadvertencia',
            name='descricao_padrao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tipoadvertencia',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='treinamentofuncionario',
            name='data_realizacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='treinamentofuncionario',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treinamentofuncionario',
            name='nome_treinamento',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='setor',
            name='riscos',
            field=models.ManyToManyField(blank=True, to='core.riscoocupacional'),
        ),
    ]
