# Generated by Django 5.1.6 on 2026-02-08 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_riscoocupacional_remove_afastamento_criado_em_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riscoocupacional',
            old_name='descricao',
            new_name='possiveis_danos',
        ),
        migrations.RemoveField(
            model_name='riscoocupacional',
            name='nome',
        ),
        migrations.AddField(
            model_name='riscoocupacional',
            name='agente',
            field=models.CharField(default='FISICO', help_text='Ex: Ruído, Calor, Poeira, Vírus...', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riscoocupacional',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riscoocupacional',
            name='fonte_geradora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riscoocupacional',
            name='intensidade',
            field=models.CharField(choices=[('PEQUENA', 'Pequena'), ('MEDIA', 'Média'), ('GRANDE', 'Grande')], default='PEQUENA', max_length=20),
        ),
    ]
