# Generated by Django 5.1.6 on 2026-02-08 23:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_descricao_riscoocupacional_possiveis_danos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoquimico',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='produtoquimico',
            name='data_validade',
        ),
        migrations.AddField(
            model_name='produtoquimico',
            name='cas_number',
            field=models.CharField(default='', help_text='Ex: 7664-93-9', max_length=20, verbose_name='Número CAS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtoquimico',
            name='classificacao_ghs',
            field=models.CharField(default='', max_length=200, verbose_name='Classificação GHS (Separe por vírgula)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtoquimico',
            name='concentracao',
            field=models.CharField(default='', help_text='Ex: 98%, 50mg/L', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtoquimico',
            name='data_validade_fispq',
            field=models.DateField(default='2026-01-01', verbose_name='Validade da FISPQ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtoquimico',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produtoquimico',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtoquimico',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.setor'),
        ),
        migrations.AddField(
            model_name='produtoquimico',
            name='unidade',
            field=models.CharField(choices=[('L', 'Litros'), ('mL', 'Mililitros'), ('kg', 'Quilos'), ('g', 'Gramas')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtoquimico',
            name='fabricante',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='produtoquimico',
            name='localizacao',
            field=models.CharField(help_text='Ex: Armário A1', max_length=100),
        ),
        migrations.CreateModel(
            name='ExposicaoOcupacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_tolerancia', models.CharField(help_text='Ex: 1 mg/m³ (NR-15)', max_length=50)),
                ('medicao_atual', models.CharField(help_text='Ex: 0.3 mg/m³', max_length=50)),
                ('percentual_exposicao', models.IntegerField(help_text='Porcentagem em relação ao limite')),
                ('data_medicao', models.DateField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
                ('produto_quimico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produtoquimico')),
            ],
        ),
    ]
