# Generated by Django 5.1.6 on 2026-02-09 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_produtoquimico_classificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoquimico',
            name='classificacao_ghs',
            field=models.CharField(max_length=200, verbose_name='Classificação GHS (Códigos)'),
        ),
        migrations.AlterField(
            model_name='produtoquimico',
            name='localizacao',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ex: Admissional, Audiometria, Hemograma', max_length=100, verbose_name='Tipo de Exame')),
                ('data_realizacao', models.DateField(verbose_name='Data de Realização')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='exames_laudos/', verbose_name='Laudo/Documento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='core.funcionario')),
            ],
        ),
    ]
