# Generated by Django 5.1.6 on 2026-02-09 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_produtoquimico_classificacao_ghs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extintor',
            name='acesso_livre',
            field=models.BooleanField(default=True, verbose_name='Acesso Desobstruído?'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='agente',
            field=models.CharField(choices=[('AGUA', 'Água Pressurizada (AP)'), ('PQS_BC', 'Pó Químico Seco (BC) - Bicarbonato'), ('PQS_ABC', 'Pó Químico Seco (ABC) - Monofosfato'), ('CO2', 'Gás Carbônico (CO2)'), ('ESPUMA', 'Espuma Mecânica'), ('HALON', 'Agentes Limpos (Halogenados/Fe-36)'), ('METAL', 'Pó Especial (Classe D)'), ('ACETATO', 'Acetato de Potássio (Classe K)')], max_length=20, verbose_name='Agente Extintor'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='altura_instalacao',
            field=models.DecimalField(decimal_places=2, default=1.6, max_digits=4, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='capacidade',
            field=models.IntegerField(help_text='Ex: 6 para 6kg, 10 para 10L', verbose_name='Capacidade (kg/L)'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='classe',
            field=models.CharField(choices=[('A', 'Classe A (Sólidos: Papel, Madeira, Tecido)'), ('B', 'Classe B (Líquidos Inflamáveis)'), ('C', 'Classe C (Equipamentos Elétricos)'), ('D', 'Classe D (Metais Combustíveis)'), ('K', 'Classe K (Óleos e Gorduras)'), ('BC', 'Classes B/C (Líquidos e Elétricos)'), ('ABC', 'Classes A/B/C (Universal)')], max_length=5, verbose_name='Classe de Fogo'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='classe_risco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Risco do Local'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='codigo_patrimonial',
            field=models.CharField(max_length=50, verbose_name='Código/Patrimônio'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='data_proxima_manutencao',
            field=models.DateField(verbose_name='Próxima Recarga'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='data_teste_hidrostatico',
            field=models.DateField(verbose_name='Teste Hidrostático (5 anos)'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='data_ultima_manutencao',
            field=models.DateField(verbose_name='Última Recarga'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='localizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.localizacao', verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='numero_serie',
            field=models.CharField(max_length=100, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='sinalizacao_ok',
            field=models.BooleanField(default=True, verbose_name='Sinalização de Parede/Piso OK?'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='situacao',
            field=models.CharField(choices=[('ATIVO', '✅ Ativo / Operante'), ('MANUTENCAO', '🛠️ Em Manutenção'), ('DESCARREGADO', '⚠️ Descarregado / Vazio'), ('VENCIDO', '❌ Vencido')], default='ATIVO', max_length=20),
        ),
    ]
