# Generated by Django 5.1.6 on 2026-02-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_funcionario_bairro_funcionario_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='turno',
            field=models.CharField(choices=[('TURNO_1', '1º Turno (06h - 14h)'), ('TURNO_2', '2º Turno (14h - 22h)'), ('TURNO_3', '3º Turno (22h - 06h)'), ('ADM', 'Administrativo (08h - 18h)')], default='ADM', max_length=20, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(verbose_name='Data de Admissão'),
        ),
    ]
