# Generated by Django 5.1.6 on 2026-02-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_funcionario_funcao_funcionario_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='alergias',
            field=models.TextField(blank=True, null=True, verbose_name='Alergias Conhecidas'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='medicamentos',
            field=models.TextField(blank=True, null=True, verbose_name='Medicamentos em Uso'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='observacoes_saude',
            field=models.TextField(blank=True, null=True, verbose_name='Observações de Saúde'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True, verbose_name='Tipo Sanguíneo'),
        ),
    ]
