# Generated by Django 5.1.6 on 2026-02-09 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_funcionario_alergias_funcionario_medicamentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='qrcode_data',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='capacidade',
            field=models.CharField(blank=True, help_text='Ex: 2.5 pol, 30m', max_length=100, null=True, verbose_name='Capacidade/Especificação'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='codigo',
            field=models.CharField(default='SEM-CODIGO', help_text='Ex: HID-001', max_length=50, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_instalacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Instalação'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_proxima_manutencao',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Manutenção'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_ultima_manutencao',
            field=models.DateField(blank=True, null=True, verbose_name='Última Manutenção'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='fabricante',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='equipamentos_incendio/'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='pavimento',
            field=models.CharField(blank=True, help_text='Ex: Térreo', max_length=50, null=True, verbose_name='Pavimento/Andar'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='situacao',
            field=models.CharField(choices=[('OPERANTE', '✅ Operante'), ('MANUTENCAO', '🛠️ Em Manutenção'), ('DEFEITO', '⚠️ Com Defeito')], default='OPERANTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='localizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.localizacao', verbose_name='Localização (Setor)'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(help_text='Ex: Hidrante Bloco A', max_length=100, verbose_name='Nome/Identificação'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('HIDRANTE', 'Hidrante'), ('MANGUEIRA', 'Mangueira de Incêndio'), ('SPRINKLER', 'Sprinkler'), ('ALARME', 'Alarme de Incêndio'), ('DETECTOR', 'Detector de Fumaça'), ('ILUMINACAO', 'Iluminação de Emergência'), ('PORTA', 'Porta Corta-Fogo'), ('BOMBA', 'Bomba de Incêndio'), ('CENTRAL', 'Central de Alarme'), ('OUTRO', 'Outro')], default='HIDRANTE', max_length=20),
        ),
    ]
