# Generated by Django 5.1.6 on 2026-02-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_equipamento_data_validade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extintor',
            name='andar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Andar/Pavimento'),
        ),
        migrations.AddField(
            model_name='extintor',
            name='data_fabricacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fabricação'),
        ),
        migrations.AddField(
            model_name='extintor',
            name='data_instalacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Instalação'),
        ),
        migrations.AddField(
            model_name='extintor',
            name='data_ultima_inspecao',
            field=models.DateField(blank=True, null=True, verbose_name='Última Inspeção Visual'),
        ),
        migrations.AddField(
            model_name='extintor',
            name='fabricante',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='extintor',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='extintor',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor Específico'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='acesso_livre',
            field=models.BooleanField(default=True, verbose_name='Acesso Livre?'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='capacidade',
            field=models.IntegerField(help_text='Ex: 6 para 6kg', verbose_name='Capacidade (kg/L)'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='sinalizacao_ok',
            field=models.BooleanField(default=True, verbose_name='Sinalização OK?'),
        ),
    ]
