# Generated by Django 5.1.6 on 2026-02-09 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_extintor_andar_extintor_data_fabricacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArCondicionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome/Identificação')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código Tag')),
                ('tipo', models.CharField(choices=[('split', 'Split'), ('janela', 'Janela'), ('cassete', 'Cassete'), ('piso_teto', 'Piso Teto'), ('multi_split', 'Multi Split'), ('central', 'Central'), ('fan_coil', 'Fan Coil'), ('outro', 'Outro')], default='split', max_length=20)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidade_btu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Capacidade (BTU)')),
                ('gas_refrigerante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gás Refrigerante')),
                ('localizacao', models.CharField(blank=True, max_length=150, null=True)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=100, null=True)),
                ('data_ultima_manutencao', models.DateField(blank=True, null=True)),
                ('data_proxima_manutencao', models.DateField(blank=True, null=True)),
                ('data_ultima_inspecao', models.DateField(blank=True, null=True)),
                ('data_proxima_inspecao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', '✅ Ativo'), ('manutencao', '🛠️ Em Manutenção'), ('inativo', '❌ Inativo')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('laudo_tecnico', models.FileField(blank=True, null=True, upload_to='pmoc_laudos/', verbose_name='Laudo/PMOC (PDF)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoNR13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome/Identificação')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código Tag')),
                ('tipo', models.CharField(choices=[('caldeira', 'Caldeira'), ('vaso_pressao', 'Vaso de Pressão'), ('tubulacao', 'Tubulação'), ('tanque_metalico', 'Tanque Metálico'), ('compressor', 'Compressor'), ('autoclave', 'Autoclave'), ('outro', 'Outro')], default='caldeira', max_length=20)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True)),
                ('pressao_trabalho', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pressão Trabalho')),
                ('temperatura_trabalho', models.CharField(blank=True, max_length=50, null=True, verbose_name='Temp. Trabalho')),
                ('capacidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Capacidade/Volume')),
                ('localizacao', models.CharField(blank=True, max_length=150, null=True)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('data_ultima_manutencao', models.DateField(blank=True, null=True)),
                ('data_proxima_manutencao', models.DateField(blank=True, null=True)),
                ('data_ultima_inspecao', models.DateField(blank=True, null=True)),
                ('data_proxima_inspecao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', '✅ Ativo'), ('manutencao', '🛠️ Em Manutenção'), ('inativo', '❌ Inativo')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('laudo_tecnico', models.FileField(blank=True, null=True, upload_to='nr13_laudos/', verbose_name='Laudo Técnico (PDF)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
    ]
